[2024-12-20T10:17:56.653+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: training_pipeline.preprocessing manual__2024-12-20T10:17:43.352622+00:00 [queued]>
[2024-12-20T10:17:56.665+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: training_pipeline.preprocessing manual__2024-12-20T10:17:43.352622+00:00 [queued]>
[2024-12-20T10:17:56.666+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-12-20T10:17:56.688+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): preprocessing> on 2024-12-20 10:17:43.352622+00:00
[2024-12-20T10:17:56.699+0000] {standard_task_runner.py:60} INFO - Started process 3638 to run task
[2024-12-20T10:17:56.704+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'training_pipeline', 'preprocessing', 'manual__2024-12-20T10:17:43.352622+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/training_pipeline.py', '--cfg-path', '/tmp/tmpxaku4xnq']
[2024-12-20T10:17:56.706+0000] {standard_task_runner.py:88} INFO - Job 65: Subtask preprocessing
[2024-12-20T10:17:56.727+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-12-20T10:17:56.780+0000] {task_command.py:423} INFO - Running <TaskInstance: training_pipeline.preprocessing manual__2024-12-20T10:17:43.352622+00:00 [running]> on host 79bc5a4b2be6
[2024-12-20T10:17:56.893+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='training_pipeline' AIRFLOW_CTX_TASK_ID='preprocessing' AIRFLOW_CTX_EXECUTION_DATE='2024-12-20T10:17:43.352622+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-20T10:17:43.352622+00:00'
[2024-12-20T10:17:59.727+0000] {warnings.py:110} WARNING - /opt/***/src/features/preprocessing_interim_dagshub_***.py:162: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[["houses_dam", "houses_des"]].fillna(0, inplace=True)

[2024-12-20T10:17:59.729+0000] {warnings.py:110} WARNING - /opt/***/src/features/preprocessing_interim_dagshub_***.py:165: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[["deaths", "injuries"]].fillna(0, inplace=True)

[2024-12-20T10:17:59.742+0000] {warnings.py:110} WARNING - /opt/***/src/features/preprocessing_interim_dagshub_***.py:180: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  human_damages = human_damages.sort_values(by="human_damages")[

[2024-12-20T10:17:59.744+0000] {warnings.py:110} WARNING - /opt/***/src/features/preprocessing_interim_dagshub_***.py:183: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  houses_damages = houses_damages.sort_values(by="houses_damages")[

[2024-12-20T10:18:00.092+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-20T10:18:00.093+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-20T10:18:01.258+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-12-20T10:18:01.272+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=training_pipeline, task_id=preprocessing, execution_date=20241220T101743, start_date=20241220T101756, end_date=20241220T101801
[2024-12-20T10:18:01.334+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-12-20T10:18:01.383+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
