[2024-12-19T15:14:51.542+0000] {processor.py:161} INFO - Started process (PID=107) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:14:51.544+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T15:14:51.546+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:14:51.546+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:14:51.566+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:14:51.564+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 39
    default_args = {
                   ^
SyntaxError: '{' was never closed
[2024-12-19T15:14:51.567+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:14:51.598+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.060 seconds
[2024-12-19T15:25:11.400+0000] {processor.py:161} INFO - Started process (PID=106) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:25:11.402+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T15:25:11.405+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:25:11.404+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:25:11.427+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:25:11.425+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 39
    default_args = {
                   ^
SyntaxError: '{' was never closed
[2024-12-19T15:25:11.428+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:25:11.454+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.059 seconds
[2024-12-19T15:25:41.741+0000] {processor.py:161} INFO - Started process (PID=177) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:25:41.742+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T15:25:41.745+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:25:41.745+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:25:41.766+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:25:41.765+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 39
    default_args = {
                   ^
SyntaxError: '{' was never closed
[2024-12-19T15:25:41.767+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:25:41.796+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.060 seconds
[2024-12-19T15:26:12.158+0000] {processor.py:161} INFO - Started process (PID=241) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:26:12.159+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T15:26:12.162+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:26:12.162+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:26:12.195+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:26:12.193+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 39
    default_args = {
                   ^
SyntaxError: '{' was never closed
[2024-12-19T15:26:12.196+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:26:12.228+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.075 seconds
[2024-12-19T15:26:42.405+0000] {processor.py:161} INFO - Started process (PID=305) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:26:42.408+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T15:26:42.413+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:26:42.412+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:26:42.463+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:26:42.461+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 39
    default_args = {
                   ^
SyntaxError: '{' was never closed
[2024-12-19T15:26:42.465+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:26:42.508+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.110 seconds
[2024-12-19T15:27:13.043+0000] {processor.py:161} INFO - Started process (PID=369) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:27:13.045+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T15:27:13.048+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:27:13.048+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:27:13.084+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:27:13.083+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 39
    default_args = {
                   ^
SyntaxError: '{' was never closed
[2024-12-19T15:27:13.086+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:27:13.121+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.082 seconds
[2024-12-19T15:27:43.221+0000] {processor.py:161} INFO - Started process (PID=440) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:27:43.223+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T15:27:43.232+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:27:43.231+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:27:43.260+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:27:43.258+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 39
    default_args = {
                   ^
SyntaxError: '{' was never closed
[2024-12-19T15:27:43.262+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:27:43.317+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.101 seconds
[2024-12-19T15:28:13.462+0000] {processor.py:161} INFO - Started process (PID=504) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:28:13.464+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T15:28:13.467+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:28:13.466+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:28:13.489+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:28:13.487+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 39
    default_args = {
                   ^
SyntaxError: '{' was never closed
[2024-12-19T15:28:13.490+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:28:13.533+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.076 seconds
[2024-12-19T15:28:43.796+0000] {processor.py:161} INFO - Started process (PID=568) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:28:43.798+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T15:28:43.801+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:28:43.800+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:28:43.820+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:28:43.819+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 39
    default_args = {
                   ^
SyntaxError: '{' was never closed
[2024-12-19T15:28:43.821+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:28:43.849+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.062 seconds
[2024-12-19T15:29:14.481+0000] {processor.py:161} INFO - Started process (PID=632) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:29:14.483+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T15:29:14.488+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:29:14.487+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:29:14.529+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:29:14.527+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 39
    default_args = {
                   ^
SyntaxError: '{' was never closed
[2024-12-19T15:29:14.531+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:29:14.566+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.093 seconds
[2024-12-19T15:29:44.812+0000] {processor.py:161} INFO - Started process (PID=702) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:29:44.813+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T15:29:44.817+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:29:44.816+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:29:44.839+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:29:44.837+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 39
    default_args = {
                   ^
SyntaxError: '{' was never closed
[2024-12-19T15:29:44.840+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:29:44.873+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.067 seconds
[2024-12-19T15:37:22.282+0000] {processor.py:161} INFO - Started process (PID=113) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:37:22.284+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T15:37:22.286+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:37:22.286+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:37:22.304+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:37:22.302+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 39
    default_args = {
                   ^
SyntaxError: '{' was never closed
[2024-12-19T15:37:22.305+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:37:22.346+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.068 seconds
[2024-12-19T15:37:53.167+0000] {processor.py:161} INFO - Started process (PID=170) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:37:53.170+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T15:37:53.177+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:37:53.176+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:37:53.229+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:37:53.225+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 39
    default_args = {
                   ^
SyntaxError: '{' was never closed
[2024-12-19T15:37:53.231+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:37:53.295+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.138 seconds
[2024-12-19T15:38:23.630+0000] {processor.py:161} INFO - Started process (PID=241) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:38:23.632+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T15:38:23.636+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:38:23.635+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:38:23.664+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:38:23.662+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 39
    default_args = {
                   ^
SyntaxError: '{' was never closed
[2024-12-19T15:38:23.666+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:38:23.702+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.078 seconds
[2024-12-19T15:38:54.055+0000] {processor.py:161} INFO - Started process (PID=305) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:38:54.057+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T15:38:54.060+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:38:54.060+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:38:54.086+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:38:54.085+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 39
    default_args = {
                   ^
SyntaxError: '{' was never closed
[2024-12-19T15:38:54.087+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:38:54.118+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.068 seconds
[2024-12-19T15:39:04.308+0000] {processor.py:161} INFO - Started process (PID=354) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:39:04.309+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T15:39:04.312+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:39:04.312+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:39:05.092+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T15:39:05.093+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:39:05.092+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T15:39:06.018+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T15:39:06.018+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:39:06.018+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T15:39:06.024+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:39:06.020+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 34, in <module>
    from src.data.load_data_s3_dagshub_airflow import upload_all
ModuleNotFoundError: No module named 'src'
[2024-12-19T15:39:06.027+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:39:06.051+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 1.747 seconds
[2024-12-19T15:43:00.778+0000] {processor.py:161} INFO - Started process (PID=114) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:43:00.779+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T15:43:00.785+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:43:00.784+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:43:01.756+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T15:43:01.756+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:43:01.756+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T15:43:02.504+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T15:43:02.505+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:43:02.504+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T15:43:02.511+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:43:02.506+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 34, in <module>
    from src.data.load_data_s3_dagshub_airflow import upload_all
ModuleNotFoundError: No module named 'src'
[2024-12-19T15:43:02.514+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:43:02.555+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 1.784 seconds
[2024-12-19T15:43:32.719+0000] {processor.py:161} INFO - Started process (PID=182) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:43:32.721+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T15:43:32.723+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:43:32.723+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:43:32.953+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:43:32.953+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T15:43:33.162+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T15:43:33.163+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:43:33.162+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T15:43:33.362+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T15:43:33.363+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:43:33.362+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T15:43:33.372+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:43:33.365+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 34, in <module>
    from src.data.load_data_s3_dagshub_airflow import upload_all
ModuleNotFoundError: No module named 'src'
[2024-12-19T15:43:33.375+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:43:33.407+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.692 seconds
[2024-12-19T15:44:04.342+0000] {processor.py:161} INFO - Started process (PID=246) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:44:04.344+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T15:44:04.347+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:44:04.346+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:44:04.607+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:44:04.607+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T15:44:04.849+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T15:44:04.850+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:44:04.850+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T15:44:05.238+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T15:44:05.239+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:44:05.239+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T15:44:05.249+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:44:05.241+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 34, in <module>
    from src.data.load_data_s3_dagshub_airflow import upload_all
ModuleNotFoundError: No module named 'src'
[2024-12-19T15:44:05.251+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:44:05.274+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.938 seconds
[2024-12-19T15:44:35.347+0000] {processor.py:161} INFO - Started process (PID=321) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:44:35.348+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T15:44:35.351+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:44:35.350+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:44:35.557+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:44:35.557+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T15:44:35.819+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T15:44:35.820+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:44:35.820+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T15:44:36.025+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T15:44:36.026+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:44:36.026+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T15:44:36.033+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:44:36.028+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 34, in <module>
    from src.data.load_data_s3_dagshub_airflow import upload_all
ModuleNotFoundError: No module named 'src'
[2024-12-19T15:44:36.036+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:44:36.067+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.724 seconds
[2024-12-19T15:45:07.004+0000] {processor.py:161} INFO - Started process (PID=385) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:45:07.006+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T15:45:07.009+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:45:07.009+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:45:07.237+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:45:07.237+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T15:45:07.526+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T15:45:07.528+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:45:07.527+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T15:45:07.751+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T15:45:07.752+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:45:07.752+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T15:45:07.761+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:45:07.754+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 34, in <module>
    from src.data.load_data_s3_dagshub_airflow import upload_all
ModuleNotFoundError: No module named 'src'
[2024-12-19T15:45:07.763+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:45:07.797+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.800 seconds
[2024-12-19T15:45:38.045+0000] {processor.py:161} INFO - Started process (PID=453) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:45:38.048+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T15:45:38.054+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:45:38.053+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:45:38.321+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:45:38.321+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T15:45:38.613+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T15:45:38.615+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:45:38.614+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T15:45:39.058+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T15:45:39.059+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:45:39.059+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T15:45:39.068+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:45:39.061+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 34, in <module>
    from src.data.load_data_s3_dagshub_airflow import upload_all
ModuleNotFoundError: No module named 'src'
[2024-12-19T15:45:39.071+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:45:39.096+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 1.060 seconds
[2024-12-19T15:46:09.241+0000] {processor.py:161} INFO - Started process (PID=530) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:46:09.243+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T15:46:09.245+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:46:09.245+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:46:09.461+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:46:09.461+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T15:46:09.823+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T15:46:09.824+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:46:09.823+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T15:46:10.281+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T15:46:10.282+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:46:10.282+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T15:46:10.288+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:46:10.284+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 34, in <module>
    from src.data.load_data_s3_dagshub_airflow import upload_all
ModuleNotFoundError: No module named 'src'
[2024-12-19T15:46:10.289+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:46:10.312+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 1.074 seconds
[2024-12-19T15:46:40.841+0000] {processor.py:161} INFO - Started process (PID=601) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:46:40.843+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T15:46:40.848+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:46:40.847+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:46:41.106+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:46:41.106+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T15:46:41.343+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T15:46:41.344+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:46:41.343+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T15:46:41.728+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T15:46:41.729+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:46:41.729+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T15:46:41.736+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:46:41.731+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 34, in <module>
    from src.data.load_data_s3_dagshub_airflow import upload_all
ModuleNotFoundError: No module named 'src'
[2024-12-19T15:46:41.739+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:46:41.761+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.927 seconds
[2024-12-19T15:47:12.125+0000] {processor.py:161} INFO - Started process (PID=665) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:47:12.126+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T15:47:12.129+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:47:12.129+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:47:12.332+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:47:12.332+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T15:47:12.620+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T15:47:12.621+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:47:12.620+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T15:47:13.028+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T15:47:13.028+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:47:13.028+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T15:47:13.035+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:47:13.030+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 34, in <module>
    from src.data.load_data_s3_dagshub_airflow import upload_all
ModuleNotFoundError: No module named 'src'
[2024-12-19T15:47:13.037+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:47:13.059+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.940 seconds
[2024-12-19T15:47:43.822+0000] {processor.py:161} INFO - Started process (PID=753) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:47:43.824+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T15:47:43.826+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:47:43.826+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:47:44.032+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:47:44.032+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T15:47:44.222+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T15:47:44.223+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:47:44.223+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T15:47:44.773+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T15:47:44.775+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:47:44.775+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T15:47:44.782+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:47:44.778+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 34, in <module>
    from src.data.load_data_s3_dagshub_airflow import upload_all
ModuleNotFoundError: No module named 'src'
[2024-12-19T15:47:44.784+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:47:44.818+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 1.001 seconds
[2024-12-19T15:48:15.415+0000] {processor.py:161} INFO - Started process (PID=829) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:48:15.417+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T15:48:15.420+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:48:15.420+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:48:15.732+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:48:15.731+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T15:48:15.965+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T15:48:15.966+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:48:15.966+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T15:48:16.525+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T15:48:16.527+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:48:16.526+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T15:48:16.533+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:48:16.529+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 34, in <module>
    from src.data.load_data_s3_dagshub_airflow import upload_all
ModuleNotFoundError: No module named 'src'
[2024-12-19T15:48:16.535+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:48:16.563+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 1.153 seconds
[2024-12-19T15:48:46.861+0000] {processor.py:161} INFO - Started process (PID=906) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:48:46.863+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T15:48:46.870+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:48:46.869+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:48:47.069+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:48:47.069+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T15:48:47.278+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T15:48:47.279+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:48:47.279+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T15:48:47.731+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T15:48:47.732+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:48:47.732+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T15:48:47.738+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:48:47.733+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 34, in <module>
    from src.data.load_data_s3_dagshub_airflow import upload_all
ModuleNotFoundError: No module named 'src'
[2024-12-19T15:48:47.741+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:48:47.761+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.908 seconds
[2024-12-19T15:49:17.916+0000] {processor.py:161} INFO - Started process (PID=975) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:49:17.918+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T15:49:17.921+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:49:17.920+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:49:18.196+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:49:18.195+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T15:49:18.421+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T15:49:18.421+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:49:18.421+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T15:49:18.855+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T15:49:18.856+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:49:18.855+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T15:49:18.864+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:49:18.858+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 34, in <module>
    from src.data.load_data_s3_dagshub_airflow import upload_all
ModuleNotFoundError: No module named 'src'
[2024-12-19T15:49:18.866+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:49:18.896+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.984 seconds
[2024-12-19T15:49:48.950+0000] {processor.py:161} INFO - Started process (PID=1055) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:49:48.951+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T15:49:48.955+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:49:48.954+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:49:49.184+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:49:49.184+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T15:49:49.378+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T15:49:49.379+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:49:49.379+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T15:49:49.786+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T15:49:49.787+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:49:49.787+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T15:49:49.795+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:49:49.789+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 34, in <module>
    from src.data.load_data_s3_dagshub_airflow import upload_all
ModuleNotFoundError: No module named 'src'
[2024-12-19T15:49:49.796+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:49:49.816+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.871 seconds
[2024-12-19T15:50:20.425+0000] {processor.py:161} INFO - Started process (PID=1119) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:50:20.427+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T15:50:20.430+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:50:20.429+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:50:20.627+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:50:20.627+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T15:50:20.880+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T15:50:20.881+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:50:20.881+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T15:50:21.335+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T15:50:21.336+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:50:21.336+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T15:50:21.343+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:50:21.338+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 34, in <module>
    from src.data.load_data_s3_dagshub_airflow import upload_all
ModuleNotFoundError: No module named 'src'
[2024-12-19T15:50:21.345+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:50:21.371+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.949 seconds
[2024-12-19T15:50:51.994+0000] {processor.py:161} INFO - Started process (PID=1183) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:50:51.996+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T15:50:52.000+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:50:52.000+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:50:52.234+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:50:52.234+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T15:50:52.439+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T15:50:52.440+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:50:52.440+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T15:50:52.846+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T15:50:52.847+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:50:52.846+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T15:50:52.856+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:50:52.849+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 34, in <module>
    from src.data.load_data_s3_dagshub_airflow import upload_all
ModuleNotFoundError: No module named 'src'
[2024-12-19T15:50:52.858+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:50:52.890+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.901 seconds
[2024-12-19T15:51:23.089+0000] {processor.py:161} INFO - Started process (PID=1254) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:51:23.090+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T15:51:23.092+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:51:23.092+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:51:23.314+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:51:23.313+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T15:51:23.539+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T15:51:23.540+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:51:23.540+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T15:51:23.952+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T15:51:23.953+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:51:23.952+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T15:51:23.960+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:51:23.955+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 34, in <module>
    from src.data.load_data_s3_dagshub_airflow import upload_all
ModuleNotFoundError: No module named 'src'
[2024-12-19T15:51:23.962+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:51:23.992+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.907 seconds
[2024-12-19T15:53:42.018+0000] {processor.py:161} INFO - Started process (PID=114) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:53:42.021+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T15:53:42.025+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:53:42.024+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:53:43.259+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T15:53:43.260+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:53:43.259+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T15:53:44.042+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T15:53:44.043+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:53:44.042+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T15:53:44.050+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:53:44.045+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 34, in <module>
    from src.data.load_data_s3_dagshub_airflow import upload_all
ModuleNotFoundError: No module named 'src'
[2024-12-19T15:53:44.053+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:53:44.102+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 2.089 seconds
[2024-12-19T15:54:15.044+0000] {processor.py:161} INFO - Started process (PID=182) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:54:15.055+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T15:54:15.060+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:54:15.059+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:54:15.475+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:54:15.474+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T15:54:15.690+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T15:54:15.691+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:54:15.691+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T15:54:15.967+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T15:54:15.968+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:54:15.967+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T15:54:15.973+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:54:15.969+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 34, in <module>
    from src.data.load_data_s3_dagshub_airflow import upload_all
ModuleNotFoundError: No module named 'src'
[2024-12-19T15:54:15.975+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:54:16.000+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.972 seconds
[2024-12-19T15:54:46.103+0000] {processor.py:161} INFO - Started process (PID=250) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:54:46.105+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T15:54:46.107+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:54:46.107+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:54:46.321+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:54:46.320+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T15:54:46.556+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T15:54:46.557+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:54:46.557+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T15:54:46.965+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T15:54:46.966+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:54:46.966+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T15:54:46.981+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:54:46.970+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 34, in <module>
    from src.data.load_data_s3_dagshub_airflow import upload_all
ModuleNotFoundError: No module named 'src'
[2024-12-19T15:54:46.986+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:54:47.031+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.933 seconds
[2024-12-19T15:55:17.178+0000] {processor.py:161} INFO - Started process (PID=321) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:55:17.180+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T15:55:17.182+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:55:17.182+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:55:17.430+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:55:17.430+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T15:55:17.627+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T15:55:17.628+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:55:17.628+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T15:55:17.832+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T15:55:17.833+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:55:17.833+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T15:55:17.843+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:55:17.836+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 34, in <module>
    from src.data.load_data_s3_dagshub_airflow import upload_all
ModuleNotFoundError: No module named 'src'
[2024-12-19T15:55:17.845+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:55:17.875+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.702 seconds
[2024-12-19T15:55:48.118+0000] {processor.py:161} INFO - Started process (PID=385) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:55:48.136+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T15:55:48.163+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:55:48.162+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:55:48.995+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:55:48.995+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T15:55:49.338+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T15:55:49.339+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:55:49.339+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T15:55:49.578+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T15:55:49.578+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:55:49.578+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T15:55:49.585+0000] {logging_mixin.py:188} INFO - [2024-12-19T15:55:49.580+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 34, in <module>
    from src.data.load_data_s3_dagshub_airflow import upload_all
ModuleNotFoundError: No module named 'src'
[2024-12-19T15:55:49.586+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T15:55:49.610+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 1.530 seconds
[2024-12-19T18:55:59.913+0000] {processor.py:161} INFO - Started process (PID=425) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T18:55:59.914+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T18:55:59.917+0000] {logging_mixin.py:188} INFO - [2024-12-19T18:55:59.916+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T18:56:00.185+0000] {logging_mixin.py:188} INFO - [2024-12-19T18:56:00.185+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T18:56:00.453+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T18:56:00.456+0000] {logging_mixin.py:188} INFO - [2024-12-19T18:56:00.456+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T18:56:02.108+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T18:56:02.109+0000] {logging_mixin.py:188} INFO - [2024-12-19T18:56:02.109+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T18:56:02.120+0000] {logging_mixin.py:188} INFO - [2024-12-19T18:56:02.111+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 34, in <module>
    from src.data.load_data_s3_dagshub_airflow import upload_all
ModuleNotFoundError: No module named 'src'
[2024-12-19T18:56:02.122+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T18:56:02.147+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 2.237 seconds
[2024-12-19T23:38:04.441+0000] {processor.py:161} INFO - Started process (PID=459) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:38:04.456+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T23:38:04.467+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:38:04.465+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:38:06.344+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:38:06.344+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T23:38:06.840+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T23:38:06.846+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:38:06.845+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T23:38:08.540+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:38:08.542+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:38:08.541+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:38:08.556+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:38:08.544+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 34, in <module>
    from src.data.load_data_s3_dagshub_airflow import upload_all
ModuleNotFoundError: No module named 'src'
[2024-12-19T23:38:08.559+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:38:08.607+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 4.216 seconds
[2024-12-19T23:38:39.204+0000] {processor.py:161} INFO - Started process (PID=526) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:38:39.206+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T23:38:39.209+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:38:39.208+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:38:39.417+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:38:39.416+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T23:38:39.664+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T23:38:39.665+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:38:39.665+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T23:38:40.017+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:38:40.018+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:38:40.017+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:38:40.028+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:38:40.020+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 34, in <module>
    from src.data.load_data_s3_dagshub_airflow import upload_all
ModuleNotFoundError: No module named 'src'
[2024-12-19T23:38:40.031+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:38:40.050+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.850 seconds
[2024-12-19T23:39:10.300+0000] {processor.py:161} INFO - Started process (PID=594) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:39:10.302+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T23:39:10.305+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:39:10.304+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:39:10.510+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:39:10.510+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T23:39:10.745+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T23:39:10.746+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:39:10.746+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T23:39:10.948+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:39:10.949+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:39:10.949+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:39:10.958+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:39:10.951+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 34, in <module>
    from src.data.load_data_s3_dagshub_airflow import upload_all
ModuleNotFoundError: No module named 'src'
[2024-12-19T23:39:10.961+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:39:11.147+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.852 seconds
[2024-12-19T23:39:41.677+0000] {processor.py:161} INFO - Started process (PID=661) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:39:41.678+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T23:39:41.681+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:39:41.681+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:39:41.892+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:39:41.891+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T23:39:42.103+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T23:39:42.104+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:39:42.104+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T23:39:42.568+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:39:42.569+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:39:42.569+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:39:42.576+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:39:42.571+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 34, in <module>
    from src.data.load_data_s3_dagshub_airflow import upload_all
ModuleNotFoundError: No module named 'src'
[2024-12-19T23:39:42.577+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:39:42.599+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 0.926 seconds
[2024-12-19T23:39:52.719+0000] {processor.py:161} INFO - Started process (PID=709) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:39:52.721+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T23:39:52.726+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:39:52.725+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:39:52.983+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:39:52.982+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T23:39:53.206+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T23:39:53.207+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:39:53.207+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T23:39:53.604+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:39:53.605+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:39:53.604+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:39:53.709+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:39:53.710+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:39:53.710+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:39:54.055+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:39:54.056+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:39:54.056+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:39:56.744+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:39:56.738+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 75, in <module>
    tas1 >> task2 >> task3
    ^^^^
NameError: name 'tas1' is not defined
[2024-12-19T23:39:56.748+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:39:56.767+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 4.054 seconds
[2024-12-19T23:40:27.223+0000] {processor.py:161} INFO - Started process (PID=789) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:40:27.225+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T23:40:27.230+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:40:27.229+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:40:27.475+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:40:27.475+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T23:40:27.685+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T23:40:27.687+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:40:27.687+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T23:40:28.073+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:40:28.075+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:40:28.074+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:40:28.159+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:40:28.160+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:40:28.160+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:40:28.564+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:40:28.565+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:40:28.565+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:40:30.618+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:40:30.609+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 75, in <module>
    tas1 >> task2 >> task3
    ^^^^
NameError: name 'tas1' is not defined
[2024-12-19T23:40:30.627+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:40:30.667+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 3.451 seconds
[2024-12-19T23:40:47.513+0000] {processor.py:161} INFO - Started process (PID=841) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:40:47.515+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T23:40:47.517+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:40:47.517+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:40:47.759+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:40:47.759+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T23:40:48.084+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T23:40:48.085+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:40:48.084+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T23:40:48.580+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:40:48.581+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:40:48.581+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:40:48.611+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:40:48.612+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:40:48.612+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:40:49.029+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:40:49.030+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:40:49.030+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:40:51.324+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:40:51.319+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 75, in <module>
    tas1 >> task2 >> task3
    ^^^^
NameError: name 'tas1' is not defined
[2024-12-19T23:40:51.329+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:40:51.362+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 3.853 seconds
[2024-12-19T23:45:53.027+0000] {processor.py:161} INFO - Started process (PID=62) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:45:53.030+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T23:45:53.035+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:45:53.034+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:45:53.436+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:45:53.435+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T23:45:53.671+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T23:45:53.672+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:45:53.672+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T23:45:53.990+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:45:53.990+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:45:53.990+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:45:54.016+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:45:54.016+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:45:54.016+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:45:54.732+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:45:54.733+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:45:54.733+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:45:58.257+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:45:58.253+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 75, in <module>
    tas1 >> task2 >> task3
    ^^^^
NameError: name 'tas1' is not defined
[2024-12-19T23:45:58.260+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:45:58.280+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 5.258 seconds
[2024-12-19T23:46:28.542+0000] {processor.py:161} INFO - Started process (PID=162) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:46:28.543+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T23:46:28.547+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:46:28.546+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:46:28.773+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:46:28.773+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T23:46:28.971+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T23:46:28.972+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:46:28.972+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T23:46:29.167+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:46:29.168+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:46:29.167+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:46:29.201+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:46:29.202+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:46:29.201+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:46:29.809+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:46:29.810+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:46:29.810+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:46:32.321+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:46:32.316+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 75, in <module>
    tas1 >> task2 >> task3
    ^^^^
NameError: name 'tas1' is not defined
[2024-12-19T23:46:32.325+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:46:32.348+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 3.812 seconds
[2024-12-19T23:47:02.985+0000] {processor.py:161} INFO - Started process (PID=253) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:47:02.987+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T23:47:02.990+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:47:02.990+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:47:03.182+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:47:03.182+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T23:47:03.417+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T23:47:03.418+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:47:03.418+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T23:47:03.612+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:47:03.613+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:47:03.612+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:47:03.666+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:47:03.667+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:47:03.667+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:47:04.252+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:47:04.253+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:47:04.253+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:47:06.410+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:47:06.403+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 75, in <module>
    tas1 >> task2 >> task3
    ^^^^
NameError: name 'tas1' is not defined
[2024-12-19T23:47:06.416+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:47:06.444+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 3.465 seconds
[2024-12-19T23:47:36.886+0000] {processor.py:161} INFO - Started process (PID=341) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:47:36.887+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T23:47:36.890+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:47:36.889+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:47:37.093+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:47:37.093+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T23:47:37.396+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T23:47:37.397+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:47:37.397+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T23:47:37.781+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:47:37.782+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:47:37.782+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:47:37.812+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:47:37.812+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:47:37.812+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:47:38.207+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:47:38.208+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:47:38.208+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:47:40.536+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:47:40.527+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 75, in <module>
    tas1 >> task2 >> task3
    ^^^^
NameError: name 'tas1' is not defined
[2024-12-19T23:47:40.543+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:47:40.578+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 3.696 seconds
[2024-12-19T23:48:10.869+0000] {processor.py:161} INFO - Started process (PID=413) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:48:10.872+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T23:48:10.877+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:48:10.876+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:48:11.072+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:48:11.072+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T23:48:11.322+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T23:48:11.323+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:48:11.323+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T23:48:11.509+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:48:11.510+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:48:11.510+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:48:11.749+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:48:11.750+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:48:11.750+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:48:12.107+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:48:12.108+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:48:12.107+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:48:14.044+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:48:14.035+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 75, in <module>
    tas1 >> task2 >> task3
    ^^^^
NameError: name 'tas1' is not defined
[2024-12-19T23:48:14.052+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:48:14.081+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 3.219 seconds
[2024-12-19T23:48:44.368+0000] {processor.py:161} INFO - Started process (PID=492) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:48:44.369+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T23:48:44.371+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:48:44.371+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:48:44.567+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:48:44.567+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T23:48:44.860+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T23:48:44.861+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:48:44.861+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T23:48:45.082+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:48:45.082+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:48:45.082+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:48:45.121+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:48:45.122+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:48:45.122+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:48:45.775+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:48:45.777+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:48:45.777+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:48:47.923+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:48:47.917+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 75, in <module>
    tas1 >> task2 >> task3
    ^^^^
NameError: name 'tas1' is not defined
[2024-12-19T23:48:47.928+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:48:47.946+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 3.582 seconds
[2024-12-19T23:49:18.076+0000] {processor.py:161} INFO - Started process (PID=564) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:49:18.078+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T23:49:18.083+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:49:18.082+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:49:18.285+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:49:18.285+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T23:49:18.505+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T23:49:18.507+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:49:18.506+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T23:49:18.907+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:49:18.908+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:49:18.908+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:49:18.938+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:49:18.939+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:49:18.939+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:49:19.298+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:49:19.299+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:49:19.299+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:49:21.349+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:49:21.342+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 75, in <module>
    tas1 >> task2 >> task3
    ^^^^
NameError: name 'tas1' is not defined
[2024-12-19T23:49:21.354+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:49:21.381+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 3.312 seconds
[2024-12-19T23:49:52.098+0000] {processor.py:161} INFO - Started process (PID=643) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:49:52.100+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T23:49:52.105+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:49:52.104+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:49:52.311+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:49:52.311+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T23:49:52.582+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T23:49:52.583+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:49:52.582+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T23:49:52.915+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:49:52.916+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:49:52.916+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:49:52.965+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:49:52.966+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:49:52.966+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:49:53.309+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:49:53.310+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:49:53.310+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:49:55.326+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:49:55.320+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 75, in <module>
    tas1 >> task2 >> task3
    ^^^^
NameError: name 'tas1' is not defined
[2024-12-19T23:49:55.331+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:49:55.358+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 3.267 seconds
[2024-12-19T23:50:25.736+0000] {processor.py:161} INFO - Started process (PID=715) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:50:25.737+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T23:50:25.740+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:50:25.739+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:50:26.001+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:50:26.000+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T23:50:26.232+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T23:50:26.233+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:50:26.233+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T23:50:26.511+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:50:26.512+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:50:26.512+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:50:26.740+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:50:26.741+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:50:26.741+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:50:27.112+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:50:27.113+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:50:27.113+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:50:29.287+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:50:29.280+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 75, in <module>
    tas1 >> task2 >> task3
    ^^^^
NameError: name 'tas1' is not defined
[2024-12-19T23:50:29.291+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:50:29.312+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 3.580 seconds
[2024-12-19T23:50:59.598+0000] {processor.py:161} INFO - Started process (PID=798) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:50:59.599+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T23:50:59.602+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:50:59.602+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:50:59.789+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:50:59.789+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T23:51:00.027+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T23:51:00.028+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:51:00.028+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T23:51:00.225+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:51:00.226+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:51:00.226+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:51:00.454+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:51:00.455+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:51:00.455+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:51:00.799+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:51:00.800+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:51:00.800+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:51:02.851+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:51:02.843+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 75, in <module>
    tas1 >> task2 >> task3
    ^^^^
NameError: name 'tas1' is not defined
[2024-12-19T23:51:02.857+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:51:02.885+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 3.292 seconds
[2024-12-19T23:51:33.115+0000] {processor.py:161} INFO - Started process (PID=882) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:51:33.117+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T23:51:33.121+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:51:33.120+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:51:33.320+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:51:33.319+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T23:51:33.578+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T23:51:33.580+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:51:33.579+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T23:51:33.785+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:51:33.786+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:51:33.785+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:51:33.987+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:51:33.988+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:51:33.988+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:51:34.344+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:51:34.345+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:51:34.345+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:51:36.728+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:51:36.724+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 75, in <module>
    tas1 >> task2 >> task3
    ^^^^
NameError: name 'tas1' is not defined
[2024-12-19T23:51:36.730+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:51:36.748+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 3.640 seconds
[2024-12-19T23:52:07.019+0000] {processor.py:161} INFO - Started process (PID=977) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:52:07.027+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T23:52:07.030+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:52:07.030+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:52:07.284+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:52:07.284+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T23:52:07.582+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T23:52:07.584+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:52:07.583+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T23:52:07.841+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:52:07.842+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:52:07.842+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:52:08.091+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:52:08.092+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:52:08.092+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:52:08.517+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:52:08.518+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:52:08.517+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:52:10.903+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:52:10.896+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/training_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/training_pipeline.py", line 75, in <module>
    tas1 >> task2 >> task3
    ^^^^
NameError: name 'tas1' is not defined
[2024-12-19T23:52:10.908+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:52:10.937+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 3.923 seconds
[2024-12-19T23:52:17.455+0000] {processor.py:161} INFO - Started process (PID=1010) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:52:17.457+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T23:52:17.460+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:52:17.459+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:52:17.722+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:52:17.722+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T23:52:18.061+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T23:52:18.062+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:52:18.062+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T23:52:18.585+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:52:18.586+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:52:18.586+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:52:18.644+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:52:18.646+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:52:18.645+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:52:19.091+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:52:19.092+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:52:19.092+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:52:21.210+0000] {processor.py:840} INFO - DAG(s) 'my_dag_2' retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:52:21.368+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:52:21.367+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:my_dag_2
[2024-12-19T23:52:21.382+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:52:21.381+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:my_dag_2
[2024-12-19T23:52:21.392+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:52:21.392+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:my_dag_2
[2024-12-19T23:52:21.393+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:52:21.392+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-12-19T23:52:21.405+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:52:21.404+0000] {dag.py:3058} INFO - Creating ORM DAG for my_dag_2
[2024-12-19T23:52:21.416+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:52:21.416+0000] {dag.py:3823} INFO - Setting next_dagrun for my_dag_2 to 2024-10-27 00:00:00+00:00, run_after=2024-10-28 00:00:00+00:00
[2024-12-19T23:52:21.438+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 3.991 seconds
[2024-12-19T23:52:51.704+0000] {processor.py:161} INFO - Started process (PID=1082) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:52:51.707+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T23:52:51.711+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:52:51.710+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:52:51.941+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:52:51.941+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T23:52:52.220+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T23:52:52.222+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:52:52.222+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T23:52:52.578+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:52:52.580+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:52:52.579+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:52:52.630+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:52:52.631+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:52:52.631+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:52:53.000+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:52:53.001+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:52:53.001+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:52:55.060+0000] {processor.py:840} INFO - DAG(s) 'my_dag_2' retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:52:55.086+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:52:55.086+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-12-19T23:52:55.108+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:52:55.108+0000] {dag.py:3823} INFO - Setting next_dagrun for my_dag_2 to 2024-10-27 00:00:00+00:00, run_after=2024-10-28 00:00:00+00:00
[2024-12-19T23:52:55.136+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 3.439 seconds
[2024-12-19T23:53:25.499+0000] {processor.py:161} INFO - Started process (PID=1161) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:53:25.501+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T23:53:25.507+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:53:25.506+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:53:25.741+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:53:25.741+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T23:53:25.941+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T23:53:25.943+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:53:25.942+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T23:53:26.434+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:53:26.435+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:53:26.435+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:53:26.467+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:53:26.468+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:53:26.468+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:53:26.815+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:53:26.816+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:53:26.815+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:53:29.009+0000] {processor.py:840} INFO - DAG(s) 'my_dag_2' retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:53:29.033+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:53:29.033+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-12-19T23:53:29.063+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:53:29.063+0000] {dag.py:3823} INFO - Setting next_dagrun for my_dag_2 to 2024-10-27 00:00:00+00:00, run_after=2024-10-28 00:00:00+00:00
[2024-12-19T23:53:29.093+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 3.601 seconds
[2024-12-19T23:53:59.354+0000] {processor.py:161} INFO - Started process (PID=1233) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:53:59.355+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T23:53:59.358+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:53:59.358+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:53:59.555+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:53:59.554+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T23:53:59.812+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T23:53:59.813+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:53:59.813+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T23:54:00.200+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:54:00.201+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:54:00.201+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:54:00.236+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:54:00.237+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:54:00.237+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:54:00.613+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:54:00.613+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:54:00.613+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:54:02.701+0000] {processor.py:840} INFO - DAG(s) 'my_dag_2' retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:54:02.726+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:54:02.725+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-12-19T23:54:02.756+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:54:02.756+0000] {dag.py:3823} INFO - Setting next_dagrun for my_dag_2 to 2024-10-27 00:00:00+00:00, run_after=2024-10-28 00:00:00+00:00
[2024-12-19T23:54:02.788+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 3.437 seconds
[2024-12-19T23:54:33.049+0000] {processor.py:161} INFO - Started process (PID=1316) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:54:33.051+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T23:54:33.053+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:54:33.053+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:54:33.249+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:54:33.248+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T23:54:33.440+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T23:54:33.441+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:54:33.440+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T23:54:33.935+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:54:33.935+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:54:33.935+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:54:33.963+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:54:33.964+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:54:33.964+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:54:34.315+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:54:34.316+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:54:34.316+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:54:36.466+0000] {processor.py:840} INFO - DAG(s) 'my_dag_2' retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:54:36.493+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:54:36.492+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-12-19T23:54:36.515+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:54:36.515+0000] {dag.py:3823} INFO - Setting next_dagrun for my_dag_2 to 2024-10-27 00:00:00+00:00, run_after=2024-10-28 00:00:00+00:00
[2024-12-19T23:54:36.544+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 3.500 seconds
[2024-12-19T23:55:07.256+0000] {processor.py:161} INFO - Started process (PID=1407) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:55:07.257+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T23:55:07.260+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:55:07.260+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:55:07.458+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:55:07.458+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T23:55:07.649+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T23:55:07.650+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:55:07.650+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T23:55:07.996+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:55:07.997+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:55:07.997+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:55:08.030+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:55:08.030+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:55:08.030+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:55:08.373+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:55:08.374+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:55:08.374+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:55:10.821+0000] {processor.py:840} INFO - DAG(s) 'my_dag_2' retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:55:10.843+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:55:10.842+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-12-19T23:55:10.865+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:55:10.864+0000] {dag.py:3823} INFO - Setting next_dagrun for my_dag_2 to 2024-10-27 00:00:00+00:00, run_after=2024-10-28 00:00:00+00:00
[2024-12-19T23:55:10.893+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 3.642 seconds
[2024-12-19T23:55:41.675+0000] {processor.py:161} INFO - Started process (PID=1496) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:55:41.677+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T23:55:41.679+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:55:41.679+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:55:41.878+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:55:41.878+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T23:55:42.064+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T23:55:42.067+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:55:42.066+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T23:55:42.447+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:55:42.448+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:55:42.448+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:55:42.495+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:55:42.496+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:55:42.496+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:55:42.835+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:55:42.836+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:55:42.836+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:55:44.800+0000] {processor.py:840} INFO - DAG(s) 'my_dag_2' retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:55:44.830+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:55:44.830+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-12-19T23:55:44.858+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:55:44.858+0000] {dag.py:3823} INFO - Setting next_dagrun for my_dag_2 to 2024-10-27 00:00:00+00:00, run_after=2024-10-28 00:00:00+00:00
[2024-12-19T23:55:44.902+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 3.230 seconds
[2024-12-19T23:56:15.948+0000] {processor.py:161} INFO - Started process (PID=1589) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:56:15.949+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T23:56:15.952+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:56:15.951+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:56:16.205+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:56:16.205+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T23:56:16.564+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T23:56:16.565+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:56:16.565+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T23:56:17.039+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:56:17.040+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:56:17.039+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:56:17.074+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:56:17.075+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:56:17.074+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:56:17.441+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:56:17.442+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:56:17.442+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:56:19.545+0000] {processor.py:840} INFO - DAG(s) 'my_dag_2' retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:56:19.580+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:56:19.579+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-12-19T23:56:19.618+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:56:19.618+0000] {dag.py:3823} INFO - Setting next_dagrun for my_dag_2 to 2024-10-27 00:00:00+00:00, run_after=2024-10-28 00:00:00+00:00
[2024-12-19T23:56:19.643+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 3.699 seconds
[2024-12-19T23:56:50.426+0000] {processor.py:161} INFO - Started process (PID=1661) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:56:50.428+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T23:56:50.432+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:56:50.432+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:56:50.658+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:56:50.658+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T23:56:50.965+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T23:56:50.966+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:56:50.966+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T23:56:51.315+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:56:51.316+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:56:51.316+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:56:51.379+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:56:51.380+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:56:51.380+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:56:51.768+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:56:51.769+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:56:51.769+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:56:53.945+0000] {processor.py:840} INFO - DAG(s) 'my_dag_2' retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:56:53.970+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:56:53.969+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-12-19T23:56:53.993+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:56:53.993+0000] {dag.py:3823} INFO - Setting next_dagrun for my_dag_2 to 2024-10-27 00:00:00+00:00, run_after=2024-10-28 00:00:00+00:00
[2024-12-19T23:56:54.024+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 3.605 seconds
[2024-12-19T23:57:24.456+0000] {processor.py:161} INFO - Started process (PID=1742) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:57:24.459+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T23:57:24.463+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:57:24.462+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:57:24.685+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:57:24.685+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T23:57:24.881+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T23:57:24.882+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:57:24.882+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T23:57:25.249+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:57:25.250+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:57:25.250+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:57:25.313+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:57:25.315+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:57:25.314+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:57:25.657+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:57:25.659+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:57:25.658+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:57:27.821+0000] {processor.py:840} INFO - DAG(s) 'my_dag_2' retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:57:27.862+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:57:27.862+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-12-19T23:57:27.904+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:57:27.903+0000] {dag.py:3823} INFO - Setting next_dagrun for my_dag_2 to 2024-10-27 00:00:00+00:00, run_after=2024-10-28 00:00:00+00:00
[2024-12-19T23:57:27.952+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 3.502 seconds
[2024-12-19T23:57:58.165+0000] {processor.py:161} INFO - Started process (PID=1814) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:57:58.168+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T23:57:58.172+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:57:58.171+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:57:58.412+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:57:58.412+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T23:57:58.655+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T23:57:58.656+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:57:58.656+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T23:57:59.043+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:57:59.043+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:57:59.043+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:57:59.075+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:57:59.076+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:57:59.075+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:57:59.468+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:57:59.469+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:57:59.469+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:58:01.754+0000] {processor.py:840} INFO - DAG(s) 'my_dag_2' retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:58:01.777+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:58:01.777+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-12-19T23:58:01.798+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:58:01.797+0000] {dag.py:3823} INFO - Setting next_dagrun for my_dag_2 to 2024-10-27 00:00:00+00:00, run_after=2024-10-28 00:00:00+00:00
[2024-12-19T23:58:01.826+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 3.668 seconds
[2024-12-19T23:58:31.984+0000] {processor.py:161} INFO - Started process (PID=1893) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:58:31.986+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T23:58:31.991+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:58:31.990+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:58:32.210+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:58:32.209+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T23:58:32.421+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T23:58:32.422+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:58:32.422+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T23:58:32.835+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:58:32.836+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:58:32.835+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:58:32.874+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:58:32.875+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:58:32.875+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:58:33.230+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:58:33.231+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:58:33.231+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:58:35.318+0000] {processor.py:840} INFO - DAG(s) 'my_dag_2' retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:58:35.353+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:58:35.352+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-12-19T23:58:35.393+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:58:35.393+0000] {dag.py:3823} INFO - Setting next_dagrun for my_dag_2 to 2024-10-27 00:00:00+00:00, run_after=2024-10-28 00:00:00+00:00
[2024-12-19T23:58:35.437+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 3.466 seconds
[2024-12-19T23:59:05.892+0000] {processor.py:161} INFO - Started process (PID=1972) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:59:05.893+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T23:59:05.896+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:59:05.896+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:59:06.091+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:59:06.091+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T23:59:06.347+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T23:59:06.348+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:59:06.348+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T23:59:06.814+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:59:06.815+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:59:06.815+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:59:06.845+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:59:06.846+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:59:06.846+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:59:07.250+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:59:07.251+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:59:07.250+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:59:09.563+0000] {processor.py:840} INFO - DAG(s) 'my_dag_2' retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:59:09.587+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:59:09.587+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-12-19T23:59:09.617+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:59:09.617+0000] {dag.py:3823} INFO - Setting next_dagrun for my_dag_2 to 2024-10-27 00:00:00+00:00, run_after=2024-10-28 00:00:00+00:00
[2024-12-19T23:59:09.664+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 3.776 seconds
[2024-12-19T23:59:39.986+0000] {processor.py:161} INFO - Started process (PID=2053) to work on /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:59:39.989+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/training_pipeline.py for tasks to queue
[2024-12-19T23:59:39.993+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:59:39.992+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:59:40.189+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:59:40.189+0000] {tokens.py:86} WARNING - The added token already exists in the token cache, skipping
[2024-12-19T23:59:40.380+0000] {logging_mixin.py:188} INFO - Accessing as sarahlunette
[2024-12-19T23:59:40.380+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:59:40.380+0000] {helpers.py:107} INFO - Accessing as sarahlunette
[2024-12-19T23:59:40.753+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:59:40.754+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:59:40.754+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:59:40.782+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:59:40.783+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:59:40.783+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:59:41.131+0000] {logging_mixin.py:188} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the 
bucket
[2024-12-19T23:59:41.132+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:59:41.132+0000] {helpers.py:107} INFO - Client created. Use the name of the repo (Data_Atelier) as the name of the bucket
[2024-12-19T23:59:43.112+0000] {processor.py:840} INFO - DAG(s) 'my_dag_2' retrieved from /opt/airflow/dags/training_pipeline.py
[2024-12-19T23:59:43.133+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:59:43.132+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-12-19T23:59:43.155+0000] {logging_mixin.py:188} INFO - [2024-12-19T23:59:43.155+0000] {dag.py:3823} INFO - Setting next_dagrun for my_dag_2 to 2024-10-27 00:00:00+00:00, run_after=2024-10-28 00:00:00+00:00
[2024-12-19T23:59:43.178+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/training_pipeline.py took 3.200 seconds
